# Generated by Django 5.0.9 on 2026-09-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type', models.CharField(choices=[('BOOKING_CONFIRMED', 'Confirmation de rendez-vous'), ('REMINDER', 'Rappel de rendez-vous'), ('CANCELLED', 'Annulation'), ('ARRIVAL_CONFIRMED', 'Arrivée enregistrée')], max_length=30, verbose_name='type')),
                ('channel', models.CharField(choices=[('IN_APP', "Dans l'application"), ('EMAIL', 'E-mail'), ('SMS', 'SMS')], default='IN_APP', max_length=10, verbose_name='canal')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('message', models.CharField(max_length=500, verbose_name='message')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyée'), ('FAILED', 'Échec')], default='PENDING', max_length=10, verbose_name='statut')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyée le')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
