# Generated by Django 5.0.9 on 2026-09-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='référence')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='date et heure')),
                ('status', models.CharField(choices=[('BOOKED', 'Réservé'), ('CONFIRMED', 'Confirmé'), ('ARRIVED', 'Arrivé'), ('IN_CONSULTATION', 'En consultation'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Absent')], default='BOOKED', max_length=20, verbose_name='statut')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation")),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='organization.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.doctorprofile', verbose_name='médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.patientprofile', verbose_name='patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='organization.room')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='scheduling.slot', verbose_name='créneau')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='organization.specialty')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='appointments.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historique de statut',
                'verbose_name_plural': 'historiques de statut',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'scheduled_at'], name='appointment_doctor__2f3cbe_idx'),
        ),
    ]
