# Generated by Django 5.0.9 on 2026-09-17 15:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='jeton')),
                ('signature', models.CharField(max_length=64, verbose_name='signature')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='émis le')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='révoqué')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'jeton de rendez-vous',
                'verbose_name_plural': 'jetons de rendez-vous',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="heure d'arrivée")),
                ('source', models.CharField(choices=[('SCAN', 'Scan du QR code'), ('MANUAL', 'Saisie manuelle')], default='SCAN', max_length=10, verbose_name='origine')),
                ('direction_note', models.CharField(blank=True, max_length=255, verbose_name='orientation')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='appointments.appointment')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_check_ins', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
            ],
            options={
                'verbose_name': 'arrivée',
                'verbose_name_plural': 'arrivées',
                'ordering': ['-arrived_at'],
            },
        ),
    ]
