# Generated by Django 5.0.9 on 2026-09-17 15:14

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Médecin'), ('AGENT', "Agent d'accueil"), ('ADMIN', 'Administrateur')], max_length=10, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name="accès à l'admin Django")),
                ('must_change_password', models.BooleanField(default=False, verbose_name='doit changer son mot de passe')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inscrit le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('badge_number', models.CharField(max_length=30, unique=True, verbose_name='numéro de badge')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='organization.department', verbose_name="service d'affectation")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "profil agent d'accueil",
                'verbose_name_plural': "profils agents d'accueil",
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('license_number', models.CharField(max_length=40, unique=True, verbose_name="numéro d'ordre")),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('default_slot_duration', models.PositiveSmallIntegerField(default=30, verbose_name='durée de consultation (min)')),
                ('is_accepting_appointments', models.BooleanField(default=True, verbose_name='accepte les rendez-vous')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='organization.department', verbose_name='service')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='organization.room', verbose_name='salle')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='organization.specialty', verbose_name='spécialité')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil médecin',
                'verbose_name_plural': 'profils médecins',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('medical_record_number', models.CharField(max_length=20, unique=True, verbose_name='numéro de dossier')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin'), ('O', 'Autre')], max_length=1, verbose_name='genre')),
                ('national_id', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name="pièce d'identité")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('emergency_contact', models.CharField(blank=True, max_length=120, verbose_name="contact d'urgence")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil patient',
                'verbose_name_plural': 'profils patients',
            },
        ),
    ]
