# Generated by Django 5.0.9 on 2026-09-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='identifiant')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('building', models.CharField(blank=True, max_length=60, verbose_name='bâtiment')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='étage')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='identifiant')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'spécialité',
                'verbose_name_plural': 'spécialités',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nom')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='étage')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organization.department', verbose_name='service')),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
                'ordering': ['department__name', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_room_code_per_department'),
        ),
    ]
