# Generated by Django 5.0.9 on 2026-09-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('slot_duration', models.PositiveSmallIntegerField(default=30, verbose_name='durée du créneau (min)')),
                ('valid_from', models.DateField(verbose_name='valable à partir du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valable jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.doctorprofile', verbose_name='médecin')),
            ],
            options={
                'verbose_name': 'horaire',
                'verbose_name_plural': 'horaires',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(verbose_name='heure de fin')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BOOKED', 'Réservé'), ('BLOCKED', 'Bloqué')], default='AVAILABLE', max_length=10, verbose_name='statut')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='accounts.doctorprofile', verbose_name='médecin')),
                ('generated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='scheduling.doctorschedule')),
            ],
            options={
                'verbose_name': 'créneau',
                'verbose_name_plural': 'créneaux',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('start_datetime', models.DateTimeField(verbose_name='début')),
                ('end_datetime', models.DateTimeField(verbose_name='fin')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motif')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_off', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='accounts.doctorprofile', verbose_name='médecin')),
            ],
            options={
                'verbose_name': 'indisponibilité',
                'verbose_name_plural': 'indisponibilités',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['doctor', 'date', 'status'], name='scheduling__doctor__d66c35_idx'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'start_time'), name='unique_slot_per_doctor'),
        ),
        migrations.AddConstraint(
            model_name='timeoff',
            constraint=models.CheckConstraint(check=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='timeoff_start_before_end'),
        ),
    ]
